

data_manifest: 'HCPDevImgManifestBeh/datastructure_manifest.txt'
img_manifest: 'HCPDevImgManifestBeh/fmriresults01.txt'





packages:
#  structural_preproc_recommended: 
#    name: 'Structural Preprocessing Recommended'
  structural_preproc_extended: 
    name: 'Structural Preprocessing Extended'
    filters: 
      -  MNINonLinear/xfms/acpc2MNILinear.mat
#  structural_preproc_freesurfer: 
#    name: 'Structural Preprocessing FreeSurfer'
  rfmri_preproc_extended: 
    name: 'rfMRI Preprocessing Extended'
    filters: 
      - hp0_clean.nii.gz
      - '[AP][AP]2standard'
#  rfmri_preproc_recommended: 
#    name: 'rfMRI Preprocessing Recommended'

